### ISSUE TITLE
Change Color Names

### ISSUE THREAD

**Issue by hamzaolak** [hamzaolak/fast-read#16]
PrimaryColor
PrimaryDarkColor
SecondaryColor
SecondaryDarkColor
TextColor
DescriptionTextColor
MarkedColor

**Comment by cheiaych** [comment]
Did you want to change the color names in theme.js to these names in the same order?

**Comment by hamzaolak** [comment]
primaryColor: "#E1D5E7",
primaryDarkColor: "#9673A6",
secondaryColor: "#D5E8D4",
secondaryDarkColor: "#82B366",
textColor: "#1A1A1A",
descriptionTextColor: "#4D4D4D",
hoverColor: "FBFBFB",
markedColor: "#CC0000"
https://drive.google.com/file/d/1p81xdwYsmJvKX7pjuL8Jg11XefAq83LI/view?usp=sharing 
project designs

**Comment by cheiaych** [comment]
Alright I changed the values.
The changes are in pull request #18

**Comment by hamzaolak** [comment]
I write command your pr if you want we can open slack channel or you can write in whatsapp +905388274256

**Comment by cheiaych** [comment]
I only worked on this issue for an assignment so I probably won't be making any more contributions after this issue.

**Comment by hamzaolak** [comment]
Okay I commented your pull request
